### ISSUE TITLE
Pending Games show a start date

### ISSUE THREAD

**Issue by briimcfly** [Kylyote/toff-leo#23]
## Observed
Pending games show a start date 
![image](https://github.com/Kylyote/toff-leo/assets/7972240/25807cb0-eed3-4bda-89ab-545fab36eef0)

## Expected 
Only games that have started will have a START DATE
Pending games will have a CREATED DATE

**Comment by jsgunn22** [comment]
const startDate = attacker_id && defender_id ? `Started on: ${thisgamesVar}.createdAt` : `Created on: ${thisgamesVar}.createdAt` 

Buttttt then we need to get this into the game-list-item.handlebars to render as whatever the conditional decides.
currently it is just getting it from the game object.  I think there is a way to pass in additional variables... even so this is doing it in the html and #if statements are very limited
