### ISSUE TITLE
Issue Capturing King : Issue with Defender Capturing Defenders 

### ISSUE THREAD

**Issue by briimcfly** [Kylyote/toff-leo#34]
## Observed 
Attacker unable to cap king 
Defender unable to cap Attacker 

![CleanShot 2023-09-22 at 12 31 55](https://github.com/Kylyote/toff-leo/assets/7972240/a6b4a34e-b543-4c1a-9dae-893dc7759266)

**Comment by ColtonMakesStuff** [comment]
taken care of, just updated the conditions to be based off of current players piece type instead of the players playertype
