### ISSUE TITLE
Users who aren't logged in, are unable to view games 

### ISSUE THREAD

**Issue by briimcfly** [Kylyote/toff-leo#35]
## Observed
When i'm logged out, I can't click on `view game`

## Expected
I can view games even when i'm logged out .

![CleanShot 2023-09-22 at 13 29 29](https://github.com/Kylyote/toff-leo/assets/7972240/3863c86a-e85b-4f2c-b2a2-ac2cb509609f)

**Comment by jsgunn22** [comment]
This is because the only links that render a game aare in the myGames.js.  This will be easy to update.   Since the session id isnt set on users that arent logged in then i need to also update the conditional for whos turn it is which will be the Easiest of PZs
